# Generated by Django 5.0.7 on 2024-08-02 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_backgroundimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='extendedBody',
            field=models.TextField(blank=True, null=True),
        ),
    ]
