# Generated by Django 5.0.7 on 2024-08-13 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_service_extendedbody'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='image',
            new_name='cardImage',
        ),
        migrations.RenameField(
            model_name='service',
            old_name='extendedBody',
            new_name='summaryBody',
        ),
        migrations.AddField(
            model_name='service',
            name='afterImage',
            field=models.ImageField(blank=True, null=True, upload_to='service_images/'),
        ),
        migrations.AddField(
            model_name='service',
            name='beforeImage',
            field=models.ImageField(blank=True, null=True, upload_to='service_images/'),
        ),
        migrations.AddField(
            model_name='service',
            name='photoGalleryTag',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='serviceId',
            field=models.TextField(blank=True, null=True),
        ),
    ]
